import { Inter } from 'next/font/google';
import '@/public/assets/css/bootstrap.min.css';
import '@/public/assets/css/owl.css';
import '@/public/assets/css/flexslider.css';
import '@/public/assets/css/font-awesome.min.css';
import '@/public/assets/css/icomoon.css';
import '@/public/assets/css/jquery.fancybox.min.css';
import '@/public/assets/css/scss/elements/theme-css.css';
import '@/public/assets/css/style.css';
import '@/public/assets/css/woocommerce-layout.css';
import '@/public/assets/css/woocommerce.css';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Creote - Corporate & Consulting Business NextJS Template',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
